app_package/bp_blog/routes.py
from flask import Blueprint
from flask import render_template, url_for, redirect, flash, request,current_app, get_flashed_messages, \
    send_from_directory, g
import os
from datetime import datetime
import time
import logging
from logging.handlers import RotatingFileHandler
import jinja2
from flask_login import login_user, current_user, logout_user, login_required
from app_package.bp_blog.utils import create_blog_posts_list, \
    remove_MACOSX_files, check_for_dir_if_not_exist_make_dir, \
    unzip_blog_files_and_extract_to_dir,  \
    delete_old_write_new_index_html

from pw_tools import replace_code_snippet_filename_with_jinja_include_block, \
    replace_img_src_jinja, get_title, sanitize_directory_name, \
    read_html_to_soup, remove_head, remove_body_tags, replace_p_elements_with_img, \
    remove_line_height_from_p_tags, replace_span_with_background_styling_with_contents

from pw_models import DatabaseSession, text, Users, BlogPosts
from werkzeug.utils import secure_filename
import shutil
import zipfile
import jinja2
import re
from app_package._common.utilities import custom_logger, wrap_up_session

logger_bp_blog = custom_logger('bp_blog.log')
bp_blog = Blueprint('bp_blog', __name__)

@bp_blog.before_request
def before_request():
    logger_bp_blog.info("-- def before_request() --")
    # Assign a new session to a global `g` object, accessible during the whole request
    g.db_session = DatabaseSession()
    
    # Use getattr to safely access g.referrer, defaulting to None if it's not set
    if getattr(g, 'referrer', None) is None:
        if request.referrer:
            g.referrer = request.referrer
        else:
            g.referrer = "No referrer"
    
    logger_bp_blog.info("-- def before_request() END --")


## Access images for Posted articles
# @bp_blog.route('/get_post_images/<post_dir_name>/<img_dir_name>/<filename>')
@bp_blog.route('/get_post_images/<post_dir_name>/<filename>')
def get_post_files(post_dir_name,filename):
    logger_bp_blog.info(f"- in get_post_files route for {post_dir_name}/images/{filename}")
    dir = os.path.join(current_app.config.get('DIR_BLOG_POSTS'),post_dir_name, "images")
    if not os.path.exists(os.path.join(dir, filename)):
        logger_bp_blog.info(f"-----------> MISSING FILE: {os.path.join(dir, filename)} <------")

    return send_from_directory(dir, filename)

## Access icons for Linked articles
@bp_blog.route('/get_blog_icons/<filename>')
def get_blog_icons(filename):
    logger_bp_blog.info(f"- in get_blog_icons route -")
    dir = current_app.config.get('DIR_BLOG_ICONS')
    logger_bp_blog.info(f"looking for file: {os.path.join(dir, filename)}")

    if not os.path.exists(os.path.join(dir, filename)):
        logger_bp_blog.info(f"-----------> MISSING FILE: {os.path.join(dir, filename)} <------")

    return send_from_directory(dir, filename)

@bp_blog.route("/blog_home", methods=["GET"])
def blog_home():
    logger_bp_blog.info(f"- in blog index page -")
    db_session = g.db_session
    blog_posts_list = create_blog_posts_list(db_session)

    return render_template('blog/blog_home.html', blog_posts_list=blog_posts_list)

# @bp_blog.route("/view_post/<post_dir_name>")
@bp_blog.route("/blog/<post_id>")
# def view_post(post_dir_name):
def view_blogpost(post_id):
    db_session = g.db_session
    # post_id = re.findall(r'\d+', post_dir_name)
    post_dir_name = f"{int(post_id):04d}_post"
    post = db_session.get(BlogPosts,post_id)

    templates_path_lists = [
        os.path.join(current_app.config.root_path,"templates"),
        os.path.join(current_app.config.get('DIR_BLOG_POSTS'), post_dir_name)
    ]

    templateLoader = jinja2.FileSystemLoader(searchpath=templates_path_lists)

    templateEnv = jinja2.Environment(loader=templateLoader)
    template_parent = templateEnv.get_template("blog/view_blogpost.html")
    template_layout = templateEnv.get_template("_layout.html")
    # template_post_index = templateEnv.get_template("index.html")

    # Delete if, keep else after editing BlogPost model and moving data
    # if post.word_doc_to_html_filename != None:
    #     print("post.word_doc_to_html_filename: ", post.word_doc_to_html_filename)
    #     template_post_index = templateEnv.get_template(post.word_doc_to_html_filename)
    # else:
    template_post_index = templateEnv.get_template(post.post_html_filename)

    # If post has a sub folder

    # create a list called post_items_list

    #["<folder_name>/<file_name>"]

    return template_parent.render(template_layout=template_layout, template_post_index=template_post_index, \
        # post_id_name_string=post_id_name_string, \
        post_dir_name=post_dir_name, \
        url_for=url_for, get_flashed_messages=get_flashed_messages, current_user=current_user)


# formerly blog_user_home
@bp_blog.route("/manage_blogposts", methods=["GET","POST"])
@login_required
def manage_blogposts():
    print('--- In  manage_blogposts ----')
    logger_bp_blog.info(f"- In manage_blogposts -")
    db_session = g.db_session
    if not current_user.is_authenticated:
        return redirect(url_for('bp_main.home'))

    # all_my_posts=sess_users.query(BlogPosts).filter_by(user_id=current_user.id).all()
    all_my_posts=db_session.query(BlogPosts).filter_by(user_id=current_user.id).all()
    posts_details_list=[]
    for i in all_my_posts:
        # if i.word_doc_to_html_filename != None:
        #     posts_details_list.append([i.id, i.title, i.date_published.strftime("%m/%d/%Y"),
        #         i.description, i.word_doc_to_html_filename])
        # else:
        #     posts_details_list.append([i.id, i.title, i.date_published.strftime("%m/%d/%Y"),
        #         i.description, "link details"])
        if i.type_for_blogpost_home == "article":
            posts_details_list.append([i.id, i.title, i.date_published.strftime("%m/%d/%Y"),
                i.description, "Edit article details"])
        else:
            posts_details_list.append([i.id, i.title, i.date_published.strftime("%m/%d/%Y"),
                i.description, "Edit link details"])
    
    column_names=['id', 'Title', 'Delete','Date Pub',
         'Description','Edit Post']

    if request.method == 'POST':
        formDict=request.form.to_dict()
        print('formDict::', formDict)
        if formDict.get('delete_record_id')!='':
            post_id=formDict.get('delete_record_id')
            print(post_id)

            return redirect(url_for('bp_blog.blog_delete', post_id=post_id))

    return render_template('blog/manage_blogposts.html', posts_details_list=posts_details_list, len=len,
        column_names=column_names)


@bp_blog.route("/create_post", methods=["GET","POST"])
@login_required
def create_post():
    if not current_user.is_authenticated:
        return redirect(url_for('bp_main.home'))

    logger_bp_blog.info(f"- user has blog post permission -")
    db_session = g.db_session

    default_date = datetime.utcnow().strftime("%Y-%m-%d")

    if request.method == 'POST':
        formDict = request.form.to_dict()
        request_files = request.files

        if formDict.get('what_kind_of_post') == 'post_article_mult_files':
            logger_bp_blog.info(f"- post_article_mult_files -")

            uploaded_html_file = request_files["post_article_mult_file_html_file"]

            # create new_blogpost to get post_id number
            new_blogpost = BlogPosts(user_id=current_user.id)
            
            db_session.add(new_blogpost)
            db_session.flush()
            # create post_id string
            new_blog_id = new_blogpost.id
            new_post_dir_name = f"{new_blog_id:04d}_post"

            new_blogpost.post_dir_name = new_post_dir_name
            new_blogpost.post_html_filename = uploaded_html_file.filename
            new_blogpost.type_for_blogpost_home="article"

            # make temproary directory called 'temp_zip' to hold the uploaded zip file
            temp_zip_db_fp = os.path.join(current_app.config.get('DIR_BLOG'),'temp_zip')
            check_for_dir_if_not_exist_make_dir(temp_zip_db_fp)

            # make name and directory for path of new post dir NAME 00##_post
            # new_blog_dir_fp = os.path.join(current_app.config.get('DIR_BLOG_POSTS'), new_post_dir_name)
            new_blog_dir_file_path = os.path.join(current_app.config.get('DIR_BLOG_POSTS'), new_post_dir_name)
            check_for_dir_if_not_exist_make_dir(new_blog_dir_file_path)
            logger_bp_blog.info(f"- new_blog_dir_file_path (now exists): {new_blog_dir_file_path} -")

            new_blog_post_path_and_file_name = os.path.join(new_blog_dir_file_path,new_blogpost.post_html_filename)

            #save html file in destination
            uploaded_html_file.save(os.path.join(current_app.config.get('DIR_BLOG_POSTS'), new_post_dir_name, uploaded_html_file.filename))

            # Save zip files to temp
            if request_files.get("post_article_mult_file_image_zip_file"):

                # new_blogpost.images_dir_name = "images"
                new_blogpost.has_images= True

                post_images_zip = request_files.get("post_article_mult_file_image_zip_file")
                post_images_zip_filename = post_images_zip.filename
                post_images_zip.save(os.path.join(temp_zip_db_fp, secure_filename(post_images_zip_filename)))
                post_images_zip_folder_name_nospaces = post_images_zip_filename.replace(" ", "_")
                # dir_name_for_unzip_and_extract = os.path.join(temp_zip_db_fp, post_images_zip_folder_name_nospaces)

                # decompress uploaded IMAGES file in temp_zip
                unzip_blog_files_and_extract_to_dir(temp_zip_db_fp, post_images_zip_folder_name_nospaces, "images")

                # Remove any __MACOSX dir or files
                unzipped_temp_dir = os.path.join(temp_zip_db_fp, "images")
                remove_MACOSX_files(unzipped_temp_dir)

app_package/bp_main/routes.py
from flask import Blueprint
from flask import render_template, send_from_directory, current_app, url_for,  \
    get_flashed_messages
from flask_login import login_required, login_user, logout_user, current_user
import os
import jinja2
import csv
from app_package._common.utilities import custom_logger, wrap_up_session

logger_bp_main = custom_logger('bp_main.log')

bp_main = Blueprint('bp_main', __name__)



@bp_main.route("/", methods=["GET","POST"])
def home():
    logger_bp_main.info(f"-- in home page route --")

    # Read last 7 days activities summary
    recent_activities = None
    try:
        project_resources_root = current_app.config.get('PROJECT_RESOURCES_ROOT')
        summary_file_path = os.path.join(project_resources_root, 'left-off-summarizer', 'last-7-days-activities-summary.md')

        if os.path.exists(summary_file_path):
            with open(summary_file_path, 'r', encoding='utf-8') as f:
                recent_activities = f.read().strip()
            logger_bp_main.info(f"Successfully loaded recent activities summary from {summary_file_path}")
        else:
            logger_bp_main.warning(f"Recent activities summary file not found: {summary_file_path}")
    except Exception as e:
        logger_bp_main.error(f"Error reading recent activities summary: {str(e)}")

    # Read project time entries
    project_time_data = None
    try:
        project_resources_root = current_app.config.get('PROJECT_RESOURCES_ROOT')
        csv_file_path = os.path.join(project_resources_root, 'toggl-service', 'project_time_entries.csv')
        logger_bp_main.info(f"---- WE ARE HERE ----")

        if os.path.exists(csv_file_path):
            with open(csv_file_path, 'r', encoding='utf-8') as f:
                csv_reader = csv.DictReader(f)
                projects = []
                for row in csv_reader:
                    projects.append({
                        'name': row['project_name'],
                        'hours': float(row['total_hours'])
                    })
                # Sort alphabetically by project name
                projects.sort(key=lambda x: x['name'])
                project_time_data = projects
            logger_bp_main.info(f"Successfully loaded project time entries from {csv_file_path}")
        else:
            logger_bp_main.warning(f"Project time entries file not found: {csv_file_path}")
    except Exception as e:
        logger_bp_main.error(f"Error reading project time entries: {str(e)}")

    return render_template('main/home.html', recent_activities=recent_activities, project_time_data=project_time_data)

@bp_main.route("/about", methods=["GET","POST"])
def about():
    logger_bp_main.info(f"-- in about page route --")

    return render_template('main/about.html')

@bp_main.route("/resume", methods=["GET","POST"])
def resume():
    logger_bp_main.info(f"-- in resume route --")

    return render_template('main/resume.html')


@bp_main.route("/about_this_page", methods=["GET","POST"])
def about_this_page():
    logger_bp_main.info(f"-- in about page route --")

    return render_template('main/about_this_site.html')

@bp_main.route("/<page>", methods=["GET","POST"])
def pages(page):
    logger_bp_main.info(f"-- in {page} route --")

    return render_template('main/pages.html', page=page)


# Website Assets static data
@bp_main.route('/website_assets_favicon/<filename>')
def website_assets_favicon(filename):
    logger_bp_main.info("-- in website_assets_favicon -")
    dir = current_app.config.get('DIR_ASSETS_FAVICONS')
    logger_bp_main.info(f"file_to_server: {os.path.join(dir, filename)}")
    return send_from_directory(dir, filename)

# Media all images, videos, resume, etc.,
@bp_main.route('/media/<filename>')
def media(filename):
    logger_bp_main.info("-- in media -")
    dir = current_app.config.get('DIR_MEDIA')
    logger_bp_main.info(f"file_to_server: {os.path.join(dir, filename)}")
    return send_from_directory(dir, filename)

# # Media all images, videos, resume, etc.,
# @bp_main.route('/blog_icons/<filename>')
# def blog_icons(filename):
#     logger_bp_main.info("-- in blog_icons -")
#     dir = current_app.config.get('DIR_BLOG_ICONS')
#     logger_bp_main.info(f"file_to_server: {os.path.join(dir, filename)}")
#     return send_from_directory(dir, filename)



# never used
# # Website Files static data
# @bp_main.route('/website_files/<filename>')
# def website_files(filename):
#     print("-- entered website_files -")
#     return send_from_directory(current_app.config.get('DIR_DB_AUX_FILES_WEBSITE'), filename)

app_package/templates/_layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
  <script src="https://kit.fontawesome.com/dd4fc26679.js" crossorigin="anonymous"></script>
  
  <!-- Added bootstrap -->
  <link rel="stylesheet" href="../static/additional_styling/bootstrap-5.3.2-dist/css/bootstrap.min.css">
  <script src="../static/additional_styling/bootstrap-5.3.2-dist/js/bootstrap.min.js"></script>

 



  <!-- LinkedIn Links -->
  <meta name="theme-color" content="#000000">
  <meta 
  property="og:title"
  content="Nick Rodriguez"
/><meta 
  name="image"
  property="og:image"
  content="{{ url_for('bp_main.website_assets_favicon', filename='logo02_whiteBck-1200x627.png') }}"
/><meta 
  name="author"
  content="Nick Rodriguez"
/><meta 
  property="og:description"
  content="About your boy!"
/><meta 
  property="og:url"
  content="https://nick-rodriguez.info"
/>
  <!-- icon for iPhone  shortcut -->
  <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('bp_main.website_assets_favicon', filename='logo02_whiteBck-180x112.png') }}">
  <!-- favicon - image on tabs of browser pages-->
  <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('bp_main.website_assets_favicon', filename='favicon-nr-32x32.png') }}">





  <title>Nick Rodriguez</title>
</head>

<body>
  <div id="navbar_top" class="navbar_top" >
    <div class="div_hamburger">
      <button id="hamburger"  onclick="toggleMenu()"><i class="fas fa-bars" id="btn"></i></button>
    </div>
  </div><!-- navbar_top -->

  <!-- Slides out on small screen -->
  <div id="navbar_side" class="navbar_side navbar_side_hidden">
    <div class="div_close">
      <button class="btn_close" onclick="toggleMenu()"><i class="fa-solid fa-xmark"></i></button>
    </div>
    <div class="div_logo">
      <img class="img_logo" src="{{ url_for('bp_main.website_assets_favicon', filename='logo03_white.png')}}"/>
    </div>
    <div class="navbar_list">
      <ul>
        <li><a href="{{ url_for('bp_main.home') }}"><i class="fas fa-qrcode"></i>Home</a></li>
        <li><a href="{{ url_for('bp_main.about') }}"><i class="fa-regular fa-address-card"></i>About</a></li>
        <li><a href="{{ url_for('bp_main.resume') }}"><i class="fa-solid fa-briefcase"></i>Work and CV</a></li>
        <li><a href="{{ url_for('bp_blog.blog_home') }}"><i class="fa-brands fa-blogger"></i>Blog</a></li>
        <li><a href="{{ url_for('bp_main.about_this_page') }}"><i class="fas fa-question-circle"></i>About this page</a></li>  
        
        {% if current_user.is_authenticated %}  
          <li class="li_manage_blogpost"><a href="{{ url_for('bp_blog.manage_blogposts') }}"><i class="fa-solid fa-ghost"></i><span class="li_manage_blogpost_font">Mange blogposts</span></a></li>    
        {% endif %}  
        <!-- <li><a href="{ url_for('bp_support.openmindset') }"><i class="fas fa-question-circle"></i>Open Mindset Support</a></li>   -->
      </ul>

    </div>
  </div>

  <!-- Overlay -->
  <div id="overlay" onclick="toggleMenu()"></div>

  
  <div class="div_fixed_nav_and_main">
    <!-- Big Screen Navbar-->
    <div  class="navbar_side navbar_side_wide">
      <div class="div_logo">
        <img class="img_logo" src="{{ url_for('bp_main.website_assets_favicon', filename='logo03_white.png')}}"/>
      </div>
      <div class="navbar_list">
        <ul>
          <li><a href="{{ url_for('bp_main.home') }}"><i class="fas fa-home"></i>Home</a></li>
          <li><a href="{{ url_for('bp_main.about') }}"><i class="fa-regular fa-address-card"></i>About</a></li>
          <li><a href="{{ url_for('bp_main.resume') }}"><i class="fa-solid fa-briefcase"></i>Work and CV</a></li>
          <li><a href="{{ url_for('bp_blog.blog_home') }}"><i class="fa-brands fa-blogger"></i>Blog</a></li>
          <li><a href="{{ url_for('bp_main.about_this_page') }}"><i class="fas fa-question-circle"></i>About this page</a></li>  
          {% if current_user.is_authenticated %}  
            <li class="li_manage_blogpost"><a href="{{ url_for('bp_blog.manage_blogposts') }}"><i class="fa-solid fa-ghost"></i><span class="li_manage_blogpost_font">Mange blogposts</span></a></li>    
          {% endif %}  
          <!-- <li><a href="{ url_for('bp_support.openmindset') }"><i class="fas fa-question-circle"></i>Open Mindset Support</a></li>   -->
        </ul>
  
      </div>
    </div>

    <div class="flash_and_main">
      <div class="flash_custom_parent">

        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
    
        <div class="alert alert-{{ category }} alert_custom keep_line_break" id="div_flash">
          <i class="close icon"></i>
    
          {{ message }}
          <div class="close_right">
            <input type="button" value=&#10006 onclick="removeFlash()" class=" btn_custom02">
          </div>
    
        </div>
        {% endfor %}<!-- for category, message in messages -->
        {% endif %}<!-- if messages -->
        {% endwith %}<!-- with messages = get_flashed_messages(with_categories=true) -->
    
      </div>
  
  
      {% block main %}{% endblock %}
    </div>



  </div><!-- div_fixed_nav_and_main-->

  

  <script>
    function toggleMenu() {
      const menu = document.getElementById('navbar_side');
      const overlay = document.getElementById('overlay');

      menu.classList.toggle('navbar_side_visible');
      overlay.classList.toggle('visible');
    }
</script>

  <!-- Remove flash on click -->
  <script>
    function removeFlash() {
      const element = document.getElementById('div_flash');
      element.remove();
    }
  </script>
</body>
</html>

app_package/templates/_layout_support.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="{{ url_for('static', filename='/css/style.css') }}">
  <script src="https://kit.fontawesome.com/dd4fc26679.js" crossorigin="anonymous"></script>
  
  <!-- Recaptcha -->
  <script src="https://www.google.com/recaptcha/api.js"></script>
  <script>
    function onSubmit(token) {
      document.getElementById("send_message_form").submit();
    }
  </script>
  


  <!-- Added bootstrap -->
  <link rel="stylesheet" href="../static/additional_styling/bootstrap-5.3.2-dist/css/bootstrap.min.css">
  <script src="../static/additional_styling/bootstrap-5.3.2-dist/js/bootstrap.min.js"></script>

  <link rel="icon" href="{{ url_for('bp_main.website_assets_favicon', filename='iconOpenMindsetWhiteBack.png') }}" type="image/x-icon">
  <title>Open Mindset</title>
</head>

<body>


    <div class="main_support">

      <div class="flash_custom_parent">

        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
    
        <div class="alert alert-{{ category }} alert_custom keep_line_break" id="div_flash">
          <i class="close icon"></i>
    
          {{ message }}
          <div class="close_right">
            <input type="button" value=&#10006 onclick="removeFlash()" class=" btn_custom02">
          </div>
    
        </div>
        {% endfor %}<!-- for category, message in messages -->
        {% endif %}<!-- if messages -->
        {% endwith %}<!-- with messages = get_flashed_messages(with_categories=true) -->
    
      </div>

      <div class="main_block">
        {% block main %}{% endblock %}
      </div>

      

      <div class="footer" >
        <hr>
        <div class="div_right">
            <a href="{{ url_for('bp_main.home') }}">Back to nick-rodriguez</a>
        </div>
      </div><!-- footer -->

    </div>
  <!-- Remove flash on click -->
  <script>
    function removeFlash() {
      const element = document.getElementById('div_flash');
      element.remove();
    }
  </script>
</body>

</html>