app_package/bp_blog/routes.py
from flask import Blueprint
from flask import render_template, url_for, redirect, flash, request,current_app, get_flashed_messages, \
    send_from_directory, g
import os
from datetime import datetime
import time
import logging
from logging.handlers import RotatingFileHandler
import jinja2
from flask_login import login_user, current_user, logout_user, login_required
from app_package.bp_blog.utils import create_blog_posts_list, \
    remove_MACOSX_files, check_for_dir_if_not_exist_make_dir, \
    unzip_blog_files_and_extract_to_dir,  \
    delete_old_write_new_index_html

from pw_tools import replace_code_snippet_filename_with_jinja_include_block, \
    replace_img_src_jinja, get_title, sanitize_directory_name, \
    read_html_to_soup, remove_head, remove_body_tags, replace_p_elements_with_img, \
    remove_line_height_from_p_tags, replace_span_with_background_styling_with_contents

from pw_models import DatabaseSession, text, Users, BlogPosts
from werkzeug.utils import secure_filename
import shutil
import zipfile
import jinja2
import re
from app_package._common.utilities import custom_logger, wrap_up_session

logger_bp_blog = custom_logger('bp_blog.log')
bp_blog = Blueprint('bp_blog', __name__)

@bp_blog.before_request
def before_request():
    logger_bp_blog.info("-- def before_request() --")
    # Assign a new session to a global `g` object, accessible during the whole request
    g.db_session = DatabaseSession()
    
    # Use getattr to safely access g.referrer, defaulting to None if it's not set
    if getattr(g, 'referrer', None) is None:
        if request.referrer:
            g.referrer = request.referrer
        else:
            g.referrer = "No referrer"
    
    logger_bp_blog.info("-- def before_request() END --")


## Access images for Posted articles
# @bp_blog.route('/get_post_images/<post_dir_name>/<img_dir_name>/<filename>')
@bp_blog.route('/get_post_images/<post_dir_name>/<filename>')
def get_post_files(post_dir_name,filename):
    logger_bp_blog.info(f"- in get_post_files route for {post_dir_name}/images/{filename}")
    dir = os.path.join(current_app.config.get('DIR_BLOG_POSTS'),post_dir_name, "images")
    if not os.path.exists(os.path.join(dir, filename)):
        logger_bp_blog.info(f"-----------> MISSING FILE: {os.path.join(dir, filename)} <------")

    return send_from_directory(dir, filename)

## Access icons for Linked articles
@bp_blog.route('/get_blog_icons/<filename>')
def get_blog_icons(filename):
    logger_bp_blog.info(f"- in get_blog_icons route -")
    dir = current_app.config.get('DIR_BLOG_ICONS')
    logger_bp_blog.info(f"looking for file: {os.path.join(dir, filename)}")

    if not os.path.exists(os.path.join(dir, filename)):
        logger_bp_blog.info(f"-----------> MISSING FILE: {os.path.join(dir, filename)} <------")

    return send_from_directory(dir, filename)

@bp_blog.route("/blog_home", methods=["GET"])
def blog_home():
    logger_bp_blog.info(f"- in blog index page -")
    db_session = g.db_session
    blog_posts_list = create_blog_posts_list(db_session)

    return render_template('blog/blog_home.html', blog_posts_list=blog_posts_list)

# @bp_blog.route("/view_post/<post_dir_name>")
@bp_blog.route("/blog/<post_id>")
# def view_post(post_dir_name):
def view_blogpost(post_id):
    db_session = g.db_session
    # post_id = re.findall(r'\d+', post_dir_name)
    post_dir_name = f"{int(post_id):04d}_post"
    post = db_session.get(BlogPosts,post_id)

    templates_path_lists = [
        os.path.join(current_app.config.root_path,"templates"),
        os.path.join(current_app.config.get('DIR_BLOG_POSTS'), post_dir_name)
    ]

    templateLoader = jinja2.FileSystemLoader(searchpath=templates_path_lists)

    templateEnv = jinja2.Environment(loader=templateLoader)
    template_parent = templateEnv.get_template("blog/view_blogpost.html")
    template_layout = templateEnv.get_template("_layout.html")
    # template_post_index = templateEnv.get_template("index.html")

    # Delete if, keep else after editing BlogPost model and moving data
    # if post.word_doc_to_html_filename != None:
    #     print("post.word_doc_to_html_filename: ", post.word_doc_to_html_filename)
    #     template_post_index = templateEnv.get_template(post.word_doc_to_html_filename)
    # else:
    template_post_index = templateEnv.get_template(post.post_html_filename)

    # If post has a sub folder

    # create a list called post_items_list

    #["<folder_name>/<file_name>"]

    return template_parent.render(template_layout=template_layout, template_post_index=template_post_index, \
        # post_id_name_string=post_id_name_string, \
        post_dir_name=post_dir_name, \
        url_for=url_for, get_flashed_messages=get_flashed_messages, current_user=current_user)


# formerly blog_user_home
@bp_blog.route("/manage_blogposts", methods=["GET","POST"])
@login_required
def manage_blogposts():
    print('--- In  manage_blogposts ----')
    logger_bp_blog.info(f"- In manage_blogposts -")
    db_session = g.db_session
    if not current_user.is_authenticated:
        return redirect(url_for('bp_main.home'))

    # all_my_posts=sess_users.query(BlogPosts).filter_by(user_id=current_user.id).all()
    all_my_posts=db_session.query(BlogPosts).filter_by(user_id=current_user.id).all()
    posts_details_list=[]
    for i in all_my_posts:
        # if i.word_doc_to_html_filename != None:
        #     posts_details_list.append([i.id, i.title, i.date_published.strftime("%m/%d/%Y"),
        #         i.description, i.word_doc_to_html_filename])
        # else:
        #     posts_details_list.append([i.id, i.title, i.date_published.strftime("%m/%d/%Y"),
        #         i.description, "link details"])
        if i.type_for_blogpost_home == "article":
            posts_details_list.append([i.id, i.title, i.date_published.strftime("%m/%d/%Y"),
                i.description, "Edit article details"])
        else:
            posts_details_list.append([i.id, i.title, i.date_published.strftime("%m/%d/%Y"),
                i.description, "Edit link details"])
    
    column_names=['id', 'Title', 'Delete','Date Pub',
         'Description','Edit Post']

    if request.method == 'POST':
        formDict=request.form.to_dict()
        print('formDict::', formDict)
        if formDict.get('delete_record_id')!='':
            post_id=formDict.get('delete_record_id')
            print(post_id)

            return redirect(url_for('bp_blog.blog_delete', post_id=post_id))

    return render_template('blog/manage_blogposts.html', posts_details_list=posts_details_list, len=len,
        column_names=column_names)


@bp_blog.route("/create_post", methods=["GET","POST"])
@login_required
def create_post():
    if not current_user.is_authenticated:
        return redirect(url_for('bp_main.home'))

    logger_bp_blog.info(f"- user has blog post permission -")
    db_session = g.db_session

    default_date = datetime.utcnow().strftime("%Y-%m-%d")

    if request.method == 'POST':
        formDict = request.form.to_dict()
        request_files = request.files

        if formDict.get('what_kind_of_post') == 'post_article_mult_files':
            logger_bp_blog.info(f"- post_article_mult_files -")

            uploaded_html_file = request_files["post_article_mult_file_html_file"]

            # create new_blogpost to get post_id number
            new_blogpost = BlogPosts(user_id=current_user.id)
            
            db_session.add(new_blogpost)
            db_session.flush()
            # create post_id string
            new_blog_id = new_blogpost.id
            new_post_dir_name = f"{new_blog_id:04d}_post"

            new_blogpost.post_dir_name = new_post_dir_name
            new_blogpost.post_html_filename = uploaded_html_file.filename
            new_blogpost.type_for_blogpost_home="article"

            # make temproary directory called 'temp_zip' to hold the uploaded zip file
            temp_zip_db_fp = os.path.join(current_app.config.get('DIR_BLOG'),'temp_zip')
            check_for_dir_if_not_exist_make_dir(temp_zip_db_fp)

            # make name and directory for path of new post dir NAME 00##_post
            # new_blog_dir_fp = os.path.join(current_app.config.get('DIR_BLOG_POSTS'), new_post_dir_name)
            new_blog_dir_file_path = os.path.join(current_app.config.get('DIR_BLOG_POSTS'), new_post_dir_name)
            check_for_dir_if_not_exist_make_dir(new_blog_dir_file_path)
            logger_bp_blog.info(f"- new_blog_dir_file_path (now exists): {new_blog_dir_file_path} -")

            new_blog_post_path_and_file_name = os.path.join(new_blog_dir_file_path,new_blogpost.post_html_filename)

            #save html file in destination
            uploaded_html_file.save(os.path.join(current_app.config.get('DIR_BLOG_POSTS'), new_post_dir_name, uploaded_html_file.filename))

            # Save zip files to temp
            if request_files.get("post_article_mult_file_image_zip_file"):

                # new_blogpost.images_dir_name = "images"
                new_blogpost.has_images= True

                post_images_zip = request_files.get("post_article_mult_file_image_zip_file")
                post_images_zip_filename = post_images_zip.filename
                post_images_zip.save(os.path.join(temp_zip_db_fp, secure_filename(post_images_zip_filename)))
                post_images_zip_folder_name_nospaces = post_images_zip_filename.replace(" ", "_")
                # dir_name_for_unzip_and_extract = os.path.join(temp_zip_db_fp, post_images_zip_folder_name_nospaces)

                # decompress uploaded IMAGES file in temp_zip
                unzip_blog_files_and_extract_to_dir(temp_zip_db_fp, post_images_zip_folder_name_nospaces, "images")

                # Remove any __MACOSX dir or files
                unzipped_temp_dir = os.path.join(temp_zip_db_fp, "images")
                remove_MACOSX_files(unzipped_temp_dir)

app_package/templates/blog/blog_home.html
{% extends "_layout.html" %}
{% block title %}Blog{% endblock %}
{% block main %}

<!-- blog_index_01 branch is will rearrange blogpost so that
it will move around the the items:
wide screen: (left side: ) Title, (bottom)date; (right side) image/icon
small screen: left
-->
<!--
    This takes the blog_posts_list from the bp_blog.blog_home:
    post.0 (element 0): type_for_blogpost_home
    post.1: date
    post.2: title
    post.3: description
    post.4: blog post id (as a string)
    post.5: image_filename_for_blogpost_home
    post.6: post_dir_name
    post.7: images_dir_name
-->


  <div class="blogpost_index_page">

    <div class="blogpost_index_page_sub ">

      <div class="col_1">
        <div class="blogpost_page_title">
          <h1>Blog</h1>
        </div>
        <div class="blogpost_page_description">
          This blog contains articles as well as links to my articles hosted elsewhere.
          If the post has an icon like <span class="span_small_icon">
            <img src="{{ url_for('bp_blog.get_blog_icons',filename='medium.png') }}">
          </span>, <span class="span_small_icon">
            <img src="{{ url_for('bp_blog.get_blog_icons',filename='stack_overflow.png') }}">
          </span>, or another then it is linked outside of this page.

        </div>
        <div class="div_blogpost_index_search">
          <input type="text" id="search-bar" class="form-input input_search_bar"
          onkeyup="filterPosts()" 
          placeholder="Search blog posts...">
        </div>
        
           
        {% for post in blog_posts_list %}

        {% if post[0] == "article" %}
              <!---             -->
              <!-- Article Post -->
              <!---             -->
            
            <div class="blogpost_super">
              <div class="blogpost_a">
              <a href="{{ url_for('bp_blog.view_blogpost', post_id=post[4]) }}">
                {% include "blog/blog_home/blogpost_article.html" %}
              </a>
            </div><!-- blogpost_a-->

              <div class="blogpost_divider">
                <span class="line"></span>
              </div>

            </div><!-- blogpost_super -->

            {% else %}
              <!---          -->
              <!-- Link Post -->
              <!---          -->
              <div class="blogpost_super">
                <div class="blogpost_a">
                <a href="{{ post[4] }}">

                  {% include "blog/blog_home/blogpost_link.html" %}

                </a>
              </div><!-- blogpost_a-->

                <div class="blogpost_divider">
                  <span class="line"></span>
                </div>
              </div><!-- blogpost_super -->

      {% endif %}


      {% endfor %}

      <div class="pagination_controls">
        <button onclick="changePage(-1)">Prev</button>
        <span id="page_info"></span>
        <button onclick="changePage(1)">Next</button>
      </div>   

    </div><!-- col_1 -->

  </div><!-- blogpost_index_page_sub -->

</div><!-- blogpost_index_page -->


<script>
  function filterPosts() {
      let input = document.getElementById('search-bar');
      let filter = input.value.toUpperCase();
      let postsContainers = document.getElementsByClassName('blogpost_super');

      for (let i = 0; i < postsContainers.length; i++) {
          let container = postsContainers[i];
          let textContent = container.textContent || container.innerText;
          if (textContent.toUpperCase().indexOf(filter) > -1) {
              container.style.display = "";
          } else {
              container.style.display = "none";
          }
      }
  }

  let currentPage = 1;
  let postsPerPage = 10;
  
  window.onload = function() {
    displayPosts();
  };
  
  function displayPosts() {
    const posts = Array.from(document.getElementsByClassName('blogpost_super'));
    const totalPages = Math.ceil(posts.length / postsPerPage);
  
    // Hide all posts initially
    posts.forEach(post => post.style.display = 'none');
    
    // Calculate index range for current page
    let start = (currentPage - 1) * postsPerPage;
    let end = start + postsPerPage;
    
    // Show posts for the current page
    posts.slice(start, end).forEach(post => post.style.display = '');
  
    // Update page info
    document.getElementById('page_info').innerText = `Page ${currentPage} of ${totalPages}`;
    
    // Optionally disable navigation buttons
    document.querySelector('.pagination_controls button:nth-child(1)').disabled = currentPage === 1;
    document.querySelector('.pagination_controls button:nth-child(3)').disabled = currentPage === totalPages;
  }
  
  function changePage(direction) {
    currentPage += direction;
    displayPosts();
  }
  

</script>

{% endblock %}

app_package/templates/blog/create_post.html
{% extends "_layout.html" %}
{% block title %} Post to Blog {% endblock %}
{% block main %}
<form method="POST" id="form_create_post" enctype=multipart/form-data></form>

<div class="create_post_page">


  <div class="col_1">
    <div class="col_1_sub">

    

    <h2>Upload/Create Blog Post</h2>

    <div class="a_div_right">
      <a href="{{ url_for('bp_blog.manage_blogposts') }}" > Manage Blogs </a>
    </div>
    <div class="create_post_card">
      <div class="create_post_content">

        <div class="what_kind_of_post_div">
          <label for="action">What kind of Post?
          </label>
          <select id="action" name="what_kind_of_post" 
            onchange='onSelectChangeHandler()' form="form_create_post">
            <option value="post_article_mult_files">Blog Article - html, image zip, code zip</option>
            <option value="post_link">Link</option>
            <option value="post_article_single_zip">Blog Article - single zip</option>
          </select>
        </div>


        <!-- ------------ -->
        <!-- POST Multiple Files -->
        <!-- ------------ -->
        <div id="post_article_mult_files_id" class="post_article_mult_files_div">
          <div class="description_text_super">
            <div class="description_text">
              Zipped file with index.html<br>
              This process assumes you have:
              <ul>
                <li>started with a .docx or .odt file then converted to html (via LibreOffice)</li>

                <li>zip the images from the html file into one .zip file and upload in images input</li>
                <li>If you wish to embed another template you'll need to enter it manually with the double curly's include
                  "template_name"
                  close double curly's.</li>
                <li>zip the code snippets an upload into corresponding input below</li>

              </ul>


            </div><!--description_text-->

          </div><!-- description_text_super -->

          <div id="post_article_mult_files_inputs">


            <div class="post_article_mult_files_input_html_file">
              Upload <b>HTML</b> file:

              <input class="form-control" type="file" form="form_create_post" name="post_article_mult_file_html_file" accept=".html">

            </div><!-- post_article_single_zip_input_file -->

            <div class="post_article_mult_files_input_image_zip_file">
              Upload <b>images</b> zip file:

              <input class="form-control" type="file" form="form_create_post" name="post_article_mult_file_image_zip_file" accept=".zip">

            </div><!-- post_article_single_zip_input_file -->

            <div class="post_article_mult_files_code_zip_file">
              Upload <b>code snippets html</b> zip file:

              <input class="form-control" type="file" form="form_create_post" name="post_article_mult_file_code_zip_file" accept=".zip">

            </div><!-- post_article_single_zip_input_file -->

          </div><!-- post_article_single_zip_inputs -->

        </div><!-- post_article_single_zip_div -->









        
        <!-- ------------ -->
        <!-- POST A LINK -->
        <!-- ------------ -->
        <div id="post_link_id" class="post_link_div">
          <!-- <div class="link_stuff_div"> -->
  
            <div class="blog_link_label_div">
              <label for="blog_description">Title</label>
            </div>
            <div class="blog_link_input_div">
              <input type="text" class="form-control" name="blog_title" value="{{ title }}" form="form_create_post">
            </div>
            <div class="blog_link_label_div">
              <label for="blog_description">URL</label>
            </div>
            <div class="blog_link_input_div">
              <input type="text" class="form-control" name="blog_url" value="{{ blog_url }}" form="form_create_post">
            </div>
            <div class="blog_link_label_div">
              <label for="blog_description">Description</label>
            </div>
            <div class="blog_link_input_div">
              <textarea class="form-control" name="blog_description" id="blog_description"
                placeholder="optional (takes word doc 2nd/3rd paragraph)" form="form_create_post">{{ description }}</textarea>
            </div>
  
          </div><!-- post_a_link -->
  

        <!-- ------------ -->
        <!-- POST A ZIP -->
        <!-- ------------ -->
        <div id="post_article_single_zip_id" class="post_article_single_zip_div">
          <div class="description_text_super">
            <div class="description_text">
              Zipped file with index.html<br>
              This process assumes you have:
              <ul>
                <li><b>Requires MS Word to convert to webpage(.filtered)</b></li>
                <li>started with a Word (.docx) file then converted to webpage(.filtered) </li>
                <li>name the formerly .docx file index (i.e. index.html)</li>
                <li>Then zip/compress the index.html and the .fld directory together.</li>
                <li>If you wish to embed another template you'll need to enter it manually with the double curly's include
                  "template_name"
                  close double curly's.</li>
              </ul>


            </div><!--description_text-->

          </div><!-- description_text_super -->

          <div id="post_article_single_zip_inputs">

            <!-- <div class="new_method_input_file"> -->
            <div class="post_article_single_zip_input_file">
              Upload zipped/compressed folder (former Word document):
              <!-- <input class="form-control" type="file" form="form_create_post" name="new_method" accept=".zip"
                placeholder=".html"> -->
              <input class="form-control" type="file" form="form_create_post" name="post_article_single_zip_file" accept=".zip"
                placeholder=".html">

            </div><!-- post_article_single_zip_input_file -->

          </div><!-- post_article_single_zip_inputs -->

        </div><!-- post_article_single_zip_div -->


        <!-- </div> -->

        <div class="blog_form_bottom_buttons_and_progress">

          <div class="button_div_right">
            <input onclick="update()" type="submit" value="Upload" class="btn btn-primary btn_custom"
              form="form_create_post">
          </div>

          <div class="progress_div">
            Upload Progress Bar
            <div class="Progress_Status" id="Progress_Status">
              <div class="progress-bar progress-bar-striped" id="myprogressBar" role="progressbar"></div>
            </div><!-- Progress_Status -->
          </div><!-- progress_div -->

        </div><!-- blog_form_bottom_buttons_and_progress -->


      </div><!-- create_post_content (child of flex)-->
    </div><!-- create_post_card (flex)-->


    </div><!-- col_1_sub -->
  </div><!-- col_1-->
</div><!-- create_post_page -->


<script>
  function onSelectChangeHandler() {
    console.log("-- action activaited?");
    var val = document.getElementById("action").value;
    console.log("user selected: " + val);

    switch (val) {
      // case "old_method_with_images":
      case "post_article_mult_files":
        document.getElementById("post_article_mult_files_id").style.display = "block";
        document.getElementById("post_link_id").style.display = "none";
        document.getElementById("post_article_single_zip_id").style.display = "none";
        // document.getElementById("delete").style.display = "none";
        console.log("Add word converted to html");
        break;

      // case "zipped_html":
      case "post_link":
        document.getElementById("post_article_mult_files_id").style.display = "none";
        document.getElementById("post_link_id").style.display = "block";
        document.getElementById("post_article_single_zip_id").style.display = "none";
        // document.getElementById("delete").style.display = "none";
        console.log("Add html file");
        break;

      // case "old_method_with_images":
      case "post_article_single_zip":
        document.getElementById("post_article_mult_files_id").style.display = "none";
        document.getElementById("post_link_id").style.display = "none";
        document.getElementById("post_article_single_zip_id").style.display = "block";
        // document.getElementById("delete").style.display = "none";
        console.log("Add word converted to html");
        break;

    }
  }
</script>
<script>
  function update() {
    var element = document.getElementById("myprogressBar");
    var width = 10;
    var identity = setInterval(scene, 10);
    function scene() {
      if (width >= 100) {
        clearInterval(identity);
      } else {
        width++;
        element.style.width = width + '%';
      }
    }
  }
</script>
{% endblock %}

app_package/templates/blog/index.html
{% extends "_layout.html" %}
{% block title %}Blog{% endblock %}
{% block main %}

<!-- blog_index_01 branch is will rearrange blogpost so that
it will move around the the items:
wide screen: (left side: ) Title, (bottom)date; (right side) image/icon
small screen: left
-->

  <div class="blogpost_index_page">

    <div class="blogpost_index_page_sub ">

      <div class="col_1">
        <div class="blogpost_page_title">
          <h1>Blog</h1>
        </div>
        <div class="blogpost_page_description">
          This blog contains articles as well as links to my articles hosted elsewhere.
          If the post has an icon like <span class="span_small_icon">
            <img src="{{ url_for('bp_blog.get_blog_icons',filename='medium.png') }}">
          </span>, <span class="span_small_icon">
            <img src="{{ url_for('bp_blog.get_blog_icons',filename='stack_overflow.png') }}">
          </span>, or another then it is linked outside of this page.

        </div>
        <div class="div_blogpost_index_search">
          <input type="text" id="search-bar" class="form-input input_search_bar"
          onkeyup="filterPosts()" 
          placeholder="Search blog posts...">
        </div>
        
           
        {% for post in blog_posts_list %}

        {% if post[3][:5] != "https" %}
              <!---             -->
              <!-- Article Post -->
              <!---             -->
            
            <div class="blogpost_super">
              <div class="blogpost_a">
              <a href="{{ url_for('bp_blog.view_post', post_dir_name=post[3]) }}">
                <div class="blogpost">

                  <div class="left_side">
                    <div class="blogpost_title">
                      {{ post.1 }}
                    </div>
                    
                    {% if post.2 not in ["", None] %}
                    <div class="blogpost_description">
                      {{ post.2 }}
                    </div>
                    {% endif %}
                  </div><!-- left_side-->

                  <div class="right_side">
                    <div class="blogpost_date">
                      {{ post[0] }}
                    </div>
                  <div class="blogpost_image_super">
                    <div class="blogpost_image">
                      {% if post.6 not in ["", None] %}
                      <img class="" src="{{ url_for('bp_blog.get_post_files', post_dir_name=post.5,img_dir_name=post.6,filename=post.4) }}"/>
                      {% else %}
                      <img src="{{ url_for('bp_blog.get_blog_icons',filename=post.4) }}">
                      {% endif %}
                    </div>
                  </div>

                  </div><!-- right_side -->
                  
                </div><!-- blogpost -->
              </a>
            </div><!-- blogpost_a-->

              <div class="blogpost_divider">
                <span class="line"></span>
              </div>

            </div><!-- blogpost_super -->

            {% else %}
              <!---          -->
              <!-- Link Post -->
              <!---          -->
              <div class="blogpost_super">
                <div class="blogpost_a">
                <a href="{{ post[3] }}">

                  <div class="blogpost">

                  <div class="left_side">
                    <div class="blogpost_title">
                      {{ post.1 }}
                    </div>

                    {% if post.5 not in [None,""] %}
                    <div class="blogpost_description">
                      {{ post.5 }}
                    </div>
                    {% endif %}
                  </div><!-- left_side -->

                  <div class="right_side">
                    <div class="blogpost_date">
                      {{ post[0] }}
                    </div>

                    <div class="blogpost_image_super">
                    <div class="blogpost_image">
                      <img src="{{ url_for('bp_blog.get_blog_icons',filename=post.4) }}">
                    </div>
                    </div>
                  </div><!-- right_side -->




                  </div><!-- blogpost -->
                </a>
              </div><!-- blogpost_a-->

                <div class="blogpost_divider">
                  <span class="line"></span>
                </div>
              </div><!-- blogpost_super -->

      {% endif %}


      {% endfor %}

    </div><!-- col_1 -->

  </div><!-- blogpost_index_page_sub -->

</div><!-- blogpost_index_page -->


<script>
  function filterPosts() {
      let input = document.getElementById('search-bar');
      let filter = input.value.toUpperCase();
      let postsContainers = document.getElementsByClassName('blogpost_super');

      for (let i = 0; i < postsContainers.length; i++) {
          let container = postsContainers[i];
          let textContent = container.textContent || container.innerText;
          if (textContent.toUpperCase().indexOf(filter) > -1) {
              container.style.display = "";
          } else {
              container.style.display = "none";
          }
      }
  }
</script>

{% endblock %}

app_package/templates/blog/view_blogpost.html
{% extends "_layout.html" %}
{% block main %}

<div class="view_blogpost_page">

    <div class="view_blogpost">

        {% if current_user.is_authenticated %}
        <div class="div_right">
          <a href="{{ url_for('bp_blog.manage_blogposts') }}" > Blog User Home </a>
        </div>
        {% endif %}
        <div class="post">
          {% include template_post_index %}
        </div>
        
    </div><!-- view_blogpost -->
    
</div><!-- view_blogpost_page -->


{% endblock %}

app_package/templates/blog/view_post.html
{% extends "_layout.html" %}
{% block main %}

<div class="view_post_page">

    <div class="view_post">

        {% if current_user.is_authenticated %}
        <div class="div_right">
          <a href="{{ url_for('bp_blog.manage_blogposts') }}" > Blog User Home </a>
        </div>
        {% endif %}
        <div class="post">
          {% include template_post_index %}
        </div>
        
    </div><!-- view_post -->
    
</div><!-- view_post_page -->


{% endblock %}